name: SSH File Copy

on:
  push:
    branches:
      - main # Adjust branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download project from git
        uses: actions/checkout@v2
      - name: Build project
        run: |
          make prod-install
      - name: Prepare files
        run: |
          sudo cp -r /home/runner/work/dominosbar/dominosbar/ /tmp/dominosbar
          sudo chown -R runner:runner /tmp
      - name: Download project as artifact
        uses: actions/upload-artifact@master
        with:
          name: bundle
          path: /tmp/dominosbar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Downlaod artifact
        uses: actions/download-artifact@master
        with:
          name: bundle
          path: /tmp/dominosbar
      - name: Deploy project with SSH
        run: |
          rsync -avz --exclude 'db/postgres' /home/runner/work/dominosbar/dominosbar/ ***@***:~/ --rsh "ssh -p 22 -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=no"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          SOURCE: "../../../../../tmp/dominosbar"
          TARGET: "~/"
