name: SSH File Copy

on:
  push:
    branches:
      - main # Adjust branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download project from Git
        uses: actions/checkout@v2
      - name: Build project
        run: |
          make prod-install
      - name: Prepare files
        run: |
          mkdir -p dist
          rsync -av --exclude='db/postgres' --exclude='nextjs/node_modules' --exclude='nextjs/.next' ./ dist/
      - name: Upload project as artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: bundle
          path: dist
      - name: Deploy project with SSH
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          ARGS: '-rltgoDzvO'
          EXCLUDE: "/db/postgres/"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          SOURCE: "dist/"
          TARGET: "~/dominosbar"
