name: SSH File Copy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download project from Git
        uses: actions/checkout@v2
      - name: Test build project
        run: |
          make prod-install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy project with SSH
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          ARGS: '-rltgoDzvO'
          EXCLUDE: "/db/postgres/"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          SOURCE: "."
          TARGET: "~/dominosbar"
      - name: Run Build Commands on Server
        run: |
          ssh -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/dominosbar
            git pull origin main
            make prod-install
          EOF
